### ISSUE TITLE
命名感觉不合适

### ISSUE THREAD

**Issue by silenceleewq** [stone-info/oc-template#1]
+ (UIImage *(^)(NSString *))resizableImageWithImageName {
  return ^UIImage *(NSString *imageName) {
    UIImage *image      = [UIImage imageNamed:imageName];
    CGFloat imageWidth  = image.size.width;
    CGFloat imageHeight = image.size.height;
    return [image stretchableImageWithLeftCapWidth:(NSInteger) (imageWidth * 0.5) topCapHeight:(NSInteger) (imageHeight * 0.5)];
  };
}
这里用的是 resizable 命名, 但方法实际是对图片进行拉伸
觉得改成: stretchableImageWithImageName 比较合适.

**Comment by stone0117** [comment]
- - 你改吧... 用到这个方法的地方 都改一遍...
